import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { UserProvider } from "./(dashboard)/context/UserContext";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "Repwoop POS Software",
  description: "Generated by create Repwoop",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      
      <body
        className="font">
        <UserProvider>
        {children}
        </UserProvider>
          
        <ToastContainer />
      </body>
    </html>
  );
}
